apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-project-config
  namespace: bookstore
data:
  POSTGRES_URL: "jdbc:postgresql://postgres-service:5432/postgres"
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-project-postgres-secret
  namespace: bookstore
type: Opaque
data:
  password: YWRtaW4=
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bookstore-project-postgres-pvc
  namespace: bookstore
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-project-postgres
  namespace: bookstore
spec:
  serviceName: bookstore-project-postgres-service
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
        namespace: bookstore
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          envFrom:
            - configMapRef:
                name: bookstore-project-postgres-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-project-postgres-secret
                  key: password
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - name: bookstore-project-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: bookstore-project-postgres-data
          persistentVolumeClaim:
            claimName: bookstore-project-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: bookstore
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432

