apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-project-config
  namespace: bookstore
data:
  POSTGRES_URL: "jdbc:postgresql://db:5432/postgres"
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USER: "postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-project-secret
  namespace: bookstore
type: Opaque
data:
  password: YWRtaW4=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-project-deployment
  namespace: bookstore
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
        - name: bookstore
          image: ivamilosavljevic/mybookstore:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: bookstore-project-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-project-secret
                  key: password



