apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bookstore-statefulset
spec:
  serviceName: bookstore-project-service
  replicas: 3
  selector:
    matchLabels:
      app: bookstore-app
  template:
    metadata:
      labels:
        app: bookstore-app
    spec:
      containers:
        - name: bookstore-container
          image: ivamilosavljevic/mybookstore:latest
          ports:
            - containerPort: 80
  volumeClaimTemplates:
    - metadata:
        name: bookstore-statefulset
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi